### ISSUE TITLE
Add XStream Dependecies to ivy

### ISSUE THREAD

**Issue by bdenlinger** [rsanchez-wsu/jfiles#155] opened 2016-11-08 23:42 UTC
See title.

### Completion Goals ###
Add dependencies for version 1.4.9 and confirm build works

**Comment by bdenlinger** [comment] 2016-11-10 22:42
Ready to push to master.

**Comment by MichaelMorath** [comment] 2016-11-17 22:42
Closing because the issue is completed and merely waiting to merge to master.

**Closed as completed by MichaelMorath** 2016-11-17 22:42 UTC
